config/routes.rb
Rails.application.routes.draw do
  

  root 'entries#index'

  get 'home' => 'static_pages#home'
  
  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'
  
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :entries, only: [:create, :show]         do
    resources :comments 
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  
 

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100}
  validates :body, presence: true, length: { maximum: 140 }
  validate  :picture_size
  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
 def create
    @entry = current_user.entries.build(entry_params)
    if @entry.save
      flash[:success] = "Title created!"
      redirect_to home_url
    else
     @feed_items = []
      render 'static_pages/home'
    end
  end
  def show
     @entry = Entry.find(params[:entry_id] || params[:id])
     @comment = @entry.comments.build
  end
  def destroy
     @entry.destroy
    flash[:success] = "Title deleted"
    redirect_to request.referrer || root_url

  end
  def index
@entries = Entry.all.paginate(page: params[:page], :per_page => 10 )
  end
  private

    def entry_params
      params.require(:entry).permit(:title, :body, :picture)
    end
    def correct_user
      @entry = current_user.entries.find_by(id: params[:id])
      redirect_to root_url if @entry.nil?
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<li id="micropost-<%= entry.id %>">
  <%= link_to gravatar_for(entry.user, size: 50), entry.user %>
  <span class="user"><%= link_to entry.user.name, entry.user %></span>
  <span ><h4> Title:  <%= link_to entry.title, entry_path(entry) %></h4> </span>
  <span class="content"><%= entry.body %>
         <%= image_tag entry.picture.url if entry.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(entry.created_at) %> ago.
  <% if current_user?(entry.user) %>
      <%= link_to "delete", entry, method: :delete,
                                       data: { confirm: "You sure?" } %>
  <% end %>
  </span>
</li>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/entries/index.html.erb
<div class="row">
<div class="col-md-8">
<% if @entries.any? %>  
<h4 style="margin-left:60px"><%= "New Feed" %></h4>
<ol class="entries">
<%= render @entries %>
</ol>
<%= will_paginate @entries %>
<% end %>
</div>
</div>

app/views/entries/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/entries/show.html.erb
<% provide(:title, @entry.title) %>
<div id="micropost">
  <%= gravatar_for @entry.user%>
  <span class="user"><%= link_to @entry.user.try(:name) %></span>
  <span ><h3> Title:  <%=  @entry.title %></h3> </span>
  <span class="content"><%= @entry.body %>
         <%= image_tag @entry.picture.url if @entry.picture? %>
  </span>
  <div class="timestamp">
    Posted <%= time_ago_in_words(@entry.created_at) %> ago.
  </div>
</div>	
<%= render 'comments/comment_form' %>
<% @entry.comments.each do |comment| %>
<div class="well">
<p> <%=raw comment.content %> </p>
<div class = "pull-rigth"> Create on <%= comment.created_at %> |
Create by <%= link_to comment.user.try(:name), comment.user %>
</div>
</div>
<% end -%>	